# Generated by Django 3.2.8 on 2022-07-24 16:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_auto_20220723_1821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pita',
            new_name='Profile',
        ),
    ]
